@testset "Frozen wagers" begin
    @test check_wager_independence()
    @test check_w5_independence_family()
    @test check_w5_independence_family((2, 3, 17, 257))
    @test !check_w5_independence_family((1, 2))
    @test check_wager_conservative_extension()
    @test check_frozen_protocol_invariant()
    @test check_wager_named_models()
    @test check_w6_cycle_soundness((:s0,), ((:s0, :s0),), Set([:s0]))
    @test !check_w6_cycle_soundness((:s0, :s1), ((:s0, :s1), (:s1, :s0)), Set([:s0]))
    @test check_frozen_wager_interpretive_model()
    @test !check_frozen_wager_interpretive_model(ph=Set{Symbol}())
    @test !check_frozen_wager_interpretive_model(mat=Set{Tuple{Symbol,Symbol}}())
    @test !check_frozen_wager_interpretive_model(conscious_hinge=Set{Symbol}())
    @test check_frozen_wager_model()
    @test !check_frozen_wager_model(k0=2)
    @test !check_frozen_wager_model(sigma=Dict(:e0 => Set{Symbol}()))
    @test check_frozen_wager_full_model()
    @test !check_frozen_wager_full_model(ph=Set{Symbol}())
    @test !check_frozen_wager_full_model(k0=2)
end
