@testset "Lean Julia contract" begin
    project_root = dirname(@__DIR__)
    formal_root = joinpath(project_root, "formal", "ERIEC")
    formal_entry = read(joinpath(project_root, "formal", "ERIEC.lean"), String)

    expected_imports = [
        "Adjunction",
        "InterfaceLinearization",
        "BridgeFunctor",
        "Body",
        "Guard",
        "Closure",
        "Hinge",
        "Collapse",
        "Dynamics",
        "DC",
        "Sensitivity",
        "Value",
        "World",
        "WorldDC",
        "WorldDCRep",
        "Graded",
        "Decomp",
        "Grading",
        "Markers",
        "AnalyticFM4",
        "Invariance",
        "RefModel",
        "Wager",
        "Generation",
        "OpenDynamics",
        "Audit",
        "Lineage",
        "TheoryTranslation",
        "CertifiedArtifact",
        "Gate",
        "Gap",
        "Decay",
        "OpenSimC",
        "Centering",
        "Traceability",
        "RefModelV52",
    ]
    for module_name in expected_imports
        @test occursin("import ERIEC.$module_name", formal_entry)
    end

    contracts = [
        (
            file="Adjunction.lean",
            lean=["alpha_star", "sigma_star_induced", "sigma_star", "ERIESystem", "rigidity_of_gc", "ConvSystem", "conv_gc"],
            julia=[:alpha_star, :sigma_star_induced, :sigma_star, :ERIEStructure, :check_erie_structure, :check_relational_rigidity],
        ),
        (
            file="InterfaceLinearization.lean",
            lean=[
                "relationMatrix",
                "relationMatrix_transpose_of_converse",
                "linearizeRelation",
                "linearize_converse_eq_adjoint",
                "convSystem_linearization_eq_adjoint",
                "RealizesSensitivityAt",
                "converse_linearization_eq_sensitivity_adjoint",
                "RelationIso",
                "relationMatrix_reindex_natural",
                "RelationHom",
                "relationMatrix_lax_natural",
                "strict_naturality_fails_for_relationHom",
            ],
            julia=[
                :relation_incidence_matrix,
                :check_converse_adjoint,
                :check_relation_sensitivity_bridge,
                :check_relation_linearization_naturality,
                :check_relation_hom_lax_naturality,
                :strict_relation_hom_naturality_counterexample,
            ],
        ),
        (
            file="BridgeFunctor.lean",
            lean=[
                "HingeWitness",
                "AlphaOnlyClassifiesHinge",
                "no_alphaOnly_hinge_classifier",
                "relationGram",
                "MatrixFixedNontrivial",
                "raw_gram_bridge_counterexample",
                "hingeClassifyingLoop",
                "hingeClassifyingLoop_nontrivial_iff",
                "HingeForward",
                "hingeForward_id",
                "hingeForward_comp",
                "hingeClassifyingLoop_lax",
                "CompleteHingeData",
                "ClassifyingLoopObject",
                "hingeClassifierFunctor",
                "hingeClassifierFunctor_nontrivial_iff",
                "StrictHingeData",
                "StrictClassifyingLoopObject",
                "strictHingeClassifierFunctor",
                "strictHingeClassifier_loop_eq",
                "strictHingeClassifier_identity_intertwines",
                "strictHingeHilbertFunctor",
                "strictHingeHilbertFunctor_nontrivial_iff",
            ],
            julia=[
                :alpha_only_hinge_counterexample,
                :raw_gram_bridge_counterexample,
                :hinge_classifying_loop,
                :check_hinge_classifying_loop,
                :check_hinge_classifying_loop_lax,
                :check_hinge_classifier_functor_laws,
                :check_strict_hinge_classifier_intertwining,
                :check_hinge_hilbert_functor,
            ],
        ),
        (
            file="HilbertIntertwiner.lean",
            lean=["EndomorphismObject", "Hom", "id_map", "comp_map"],
            julia=Symbol[],
        ),
        (
            file="Gate.lean",
            lean=[
                "Gv",
                "RawEv",
                "GateEv",
                "UnknownReason",
                "DepFail",
                "Blocks",
                "promoteRaw",
                "erase_promoteRaw",
                "raw_pass_sound",
                "raw_fail_sound",
                "gate_pass_sound",
                "gate_fail_sound",
                "raw_ne_na",
                "GateFrame",
                "GateAssignment",
                "GateAssignment.gate",
                "HasBlockedPredecessor",
                "gateStep",
                "gateEv",
                "GateEquation",
                "gate_exists",
                "gate_existsUnique",
                "computedAssignment",
                "gateEv_phenomenal_range",
                "rawOnlyFrame",
                "rawOnlyAssignment",
                "DepPath",
                "na_propagates",
                "gate_na_propagates",
            ],
            julia=Symbol[],
        ),
        (
            file="Gap.lean",
            lean=[
                "alpha_forall",
                "second_gc",
                "GapUp",
                "GapDn",
                "gapUp_iff_branch",
                "gapDn_iff_empty",
                "gapUp_alpha_two",
                "no_gap_iff_singleton",
                "gap_trichotomy",
            ],
            julia=Symbol[],
        ),
        (
            file="Decay.lean",
            lean=[
                "psi",
                "psi_subset",
                "psi_strict_of_not_postfixed",
                "DecayStructure",
                "psi_isDecay",
                "dec_eq_or_strict",
                "upd_dec",
                "upd_dec_kappa_subset",
                "collapseMeasure_upd_dec_lt",
                "upd_dec_empty_absorbing",
                "iterate_upd_dec_empty_absorbing",
                "abstract_collapse",
                "collapse_of_psi",
            ],
            julia=Symbol[],
        ),
        (
            file="OpenSimC.lean",
            lean=[
                "Hom",
                "erase",
                "certify",
                "comp",
                "mapPath_comp",
                "mapPath_id_comp",
                "mapPath_comp_id",
                "Object",
                "eraseFunctor",
                "identityAuditMap",
                "identityAuditMap_noAssumptions",
            ],
            julia=Symbol[],
        ),
        (
            file="KernelOpen.lean",
            lean=[
                "Frame",
                "action_gapUp",
            ],
            julia=Symbol[],
        ),
        (
            file="Centering.lean",
            lean=[
                "Strength",
                "DynamicCompatibility",
                "ObservationCompatibility",
                "LabelCompatibility",
                "RepresentationCompatibility",
                "LabelRepresentationCompatibility",
                "CompatibilityData",
                "CompatibleIso",
                "CompatibleIso.toStatF",
                "InvariantFamily",
                "CenterSymmetry",
                "FixedCenterSymmetry",
                "invariant_fixed",
                "invariantE_fixed",
                "invariantC_fixed",
                "indist_fixed",
                "dcAtFamily",
                "dcAt_horizontal_wall",
                "horizontal_wall",
                "forallActionFamily",
                "existsActionFamily",
                "forallStateFamily",
                "existsStateFamily",
            ],
            julia=Symbol[],
        ),
        (
            file="NonDegenerateRecur.lean",
            lean=[
                "alphaRel",
                "sigmaRel",
                "gapUp",
                "gapUp_iff_branch",
                "dynFrame",
                "inducedGraph",
                "finiteInternalHorizon",
                "possibleLive",
                "e5",
                "Witness",
                "fullWitness",
                "fullWitness_has_recur",
            ],
            julia=Symbol[],
        ),
        (
            file="Traceability.lean",
            lean=[
                "TagRef",
                "Anchor",
                "Stmt",
                "DocumentAnchored",
                "VocabularyTest",
                "vocabularyStatus",
                "vocabularyStatus_complete",
                "vocabularyStatus_sound",
                "vocabularyStatus_cases",
            ],
            julia=Symbol[],
        ),
        (
            file="RefModelV52.lean",
            lean=[
                "GuaranteeIdx",
                "minimalGateAssignment",
                "minimal_gate_phenomenal_na",
                "recurrentGateAssignment",
                "recurrent_viability_passes",
                "recurrent_phenomenal_bridgeOpen",
                "standardDependency",
                "standardDependency_iff",
                "standardGateAssignment",
                "standard_gate_phenomenal_bridgeOpen",
                "alpha_sigma_converse",
                "pi_rho_converse",
                "upperRank_full",
                "fm1_false",
                "not_equiv_unit_bool",
                "Witness",
                "witness",
                "witness_nonisomorphic",
                "FullWitness",
                "fullWitness",
                "fullWitness_has_recur",
                "IntegratedWitness",
                "integratedWitness",
                "integratedWitness_has_gapUp",
                "integratedWitness_has_coupling",
                "integratedWitness_has_recur",
                "fixedCenterSymmetry",
                "HorizontalWallWitness",
                "horizontalWallWitness",
                "horizontalWallWitness_indistinguishable",
                "dc_at_all",
                "dcAt_zero_center_indistinguishable",
                "positiveValue_false",
                "positiveValue_swapped",
                "positiveValue_true",
                "markerFrame",
                "markerCoreSwap",
                "markerFixedCenterSymmetry",
                "markerConscious_horizontal_wall",
                "markerBlind_horizontal_wall",
                "analyticFrame",
                "analyticSwap",
                "analytic_eigenspace_swapped",
                "analytic_fm4_false",
                "analytic_fm4_swapped",
                "analytic_fm4_true",
                "EuclideanR2",
                "euclideanCoordinateSwapIndices",
                "euclideanCoordinateSwap",
                "euclideanSpectralProjection",
                "euclideanSpectralProjection_eq_id",
                "euclideanAnalyticFrame",
                "euclideanAnalyticSwap",
                "euclidean_hilbert_eigenspace_swapped",
                "euclidean_hilbert_fm4_false",
                "euclidean_hilbert_fm4_swapped",
                "euclidean_hilbert_fm4_true",
                "ComplexEuclideanR2",
                "complexEuclideanCoordinateSwap",
                "complexAnalyticRepresentation",
                "complexSpectralProjection",
                "complexSpectralProjection_eq_id",
                "complexAnalyticFrame",
                "complexAnalyticSwap",
                "complex_hilbert_fm4_false",
                "complex_hilbert_fm4_swapped",
                "complex_hilbert_fm4_true",
                "complexMarkerFrame",
                "complexMarkerUsesStaticInH",
                "complexHilbertFullMarker",
                "complexMarkerCoreSwap",
                "complexMarkerFixedCenterSymmetry",
                "complexMarker_fm4_iff",
                "complexMarkerConscious_horizontal_wall",
                "complexMarkerBlind_horizontal_wall",
                "complexMarker_fm4_false",
                "complexMarker_blind_false",
                "complexMarker_not_conscious_false",
                "complexMarker_blind_true",
                "complexMarker_not_conscious_true",
                "markerStep",
                "ThreeStageCollapse",
                "threeStageCollapse",
                "markerStep_zero_one",
                "markerStep_one_two",
                "markerStep_terminal",
                "markerStateEquiv",
                "markerCollapseNext",
                "markerCollapseNext_conjugates",
                "markerCollapseNext_stages",
                "markerInteroception_exchange",
                "markerStep_exchange_iff",
            ],
            julia=Symbol[],
        ),
        (
            file="AnalyticFM4.lean",
            lean=[
                "R2",
                "inner",
                "normSq",
                "coordinateSwap",
                "IsUnitary",
                "coordinateSwap_unitary",
                "coordinateSwap_normSq",
                "Frame",
                "FM4",
                "Iso",
                "eigenspace_preserved",
                "projection_preserved",
                "fm4_invariant",
                "HilbertFrame",
                "HilbertFM4",
                "HilbertIso",
                "hilbert_eigenspace_preserved",
                "hilbert_projection_preserved",
                "hilbert_fm4_invariant",
                "ComplexHilbertFrame",
                "ComplexHilbertFM4",
                "ComplexHilbertIso",
                "ComplexHilbertFullMarkerFrame",
                "complex_hilbert_eigenspace_preserved",
                "complex_hilbert_projection_preserved",
                "complex_hilbert_fm4_invariant",
                "complex_hilbert_full_marker_fm4_iff",
            ],
            julia=Symbol[],
        ),
        (
            file="StructuralHinge.lean",
            lean=[
                "CompleteHingeIso",
                "StructuralHingeData",
                "structuralToStrictFunctor",
                "structuralHingeHilbertFunctor",
                "structuralHingeHilbertFunctor_nontrivial_iff",
            ],
            julia=[:structural_hinge_isomorphism_witness],
        ),
        (
            file="ViabilityClosure.lean",
            lean=[
                "successorClosure",
                "viable_fixed",
                "ClosureStagePair",
                "viabilityClosureImage",
                "viabilityClosureImage_left_fixed",
                "viabilityClosureImage_right_fixed",
                "ViableSystemIso",
                "viabilityClosureFunctor",
                "viabilityClosureFunctor_stage_natural",
                "viabilityClosureFunctor_left_natural",
                "viabilityClosureFunctor_right_natural",
                "identityRel",
                "reflexiveStepRel",
                "RelationalClosureFrame",
                "viabilityRelationalFrame",
                "viabilityRelationalFrame_left_fixed",
                "viabilityRelationalFrame_right_fixed",
                "RelationalFrameObject",
                "RelationalFrameIso",
                "viabilityRelationalFunctor",
                "viabilityRelationalFunctor_kappa_natural",
                "viabilityRelationalFunctor_epsilon_natural",
            ],
            julia=[
                :successor_closure,
                :check_viability_closure,
                :check_viability_closure_naturality,
                :check_viability_relational_frame,
                :check_viability_relational_functor,
            ],
        ),
        (
            file="LayerComposition.lean",
            lean=[
                "relationalToHingeFunctor",
                "viableToHilbertFunctor",
                "viableToHilbert_comp_assoc",
                "viableToHilbert_nontrivial_iff",
                "viableToHilbert_maps_bool_isos_equal",
                "viableToHilbert_not_faithful",
                "no_bool_hom_left_inverse",
            ],
            julia=[
                :check_layer_composition,
                :layer_composition_nonfaithful_witness,
            ],
        ),
        (
            file="Closure.lean",
            lean=["pi_star", "rho_star", "Phi", "NuPhi", "nu", "coinduction", "nu_fixed", "finalCoalgebra"],
            julia=[:pi_star, :rho_star, :Phi, :NuPhiResult, :check_final_coalgebra],
        ),
        (
            file="Hinge.lean",
            lean=["T_prime", "Act"],
            julia=[:T_prime, :Act],
        ),
        (
            file="Collapse.lean",
            lean=["hingeCollapse"],
            julia=[:critical_slowing_score],
        ),
        (
            file="Dynamics.lean",
            lean=[
                "Conf",
                "R2Prime",
                "InternallyTotal",
                "TotalNext",
                "upd",
                "DynFrame",
                "InternalPath",
                "path_conf_iterate",
                "collapseMeasure",
                "collapse_conf",
                "total_orbit_collapse",
                "kappa_descends_strict",
                "hinge_collapse",
                "FiniteCollapse",
                "collapse",
                "Reachable",
                "downV",
                "K",
                "BdPair",
                "K_absorbing",
                "BdPair_oneway",
                "INS",
                "INS_iff_fiber",
                "coreOf",
                "Transport",
            ],
            julia=[
                :check_finite_collapse,
                :finite_update,
                :FiniteTotalNext,
                :check_total_next,
                :total_orbit_prefix,
                :finite_reachable,
                :down_to_viable,
                :check_k_absorbing,
                :finite_boundary_pairs,
                :check_boundary_oneway,
                :check_ins_mixed_fiber,
            ],
        ),
        (
            file="DC.lean",
            lean=["DC", "empty_propagation_left", "empty_propagation_right", "crit_bound"],
            julia=[:DCResult, :check_DC, :is_DC, :check_critical_bound],
        ),
        (
            file="Body.lean",
            lean=[
                "InterventionMode",
                "KernelParam",
                "SensoryFeature",
                "BodyResponse",
                "ExternalSetPoint",
                "SetPointDiagram",
                "NoTerminalSetPoint",
                "EndogenousBodyResponse",
            ],
            julia=[
                :InterventionMode,
                :KernelParam,
                :SensoryFeature,
                :BodyResponse,
                :ExternalSetPoint,
                :SetPointDiagram,
                :check_m4_no_terminal_setpoint,
                :EndogenousBodyResponse,
            ],
        ),
        (
            file="Guard.lean",
            lean=["HasTStar", "NoTStar", "hasTStar_iff_terminal", "M4", "TraceSafe", "traceSafe_to_M4Safe", "kleisli"],
            julia=[:check_terminal_guard, :check_trace_safe],
        ),
        (
            file="Sensitivity.lean",
            lean=["isDerivative", "wellDefined", "dualSymmetry", "not_id_le_adjoint_comp"],
            julia=[:sensitivity_tensor, :sensitivity_tensor_adjoint, :check_dual_symmetry, :check_adjoint_unit_counterexample],
        ),
        (
            file="Value.lean",
            lean=[
                "viabilityContribution",
                "raw_V",
                "normalized_V",
                "finiteNuPhi",
                "finiteContribution",
                "relationalNormalizedV",
                "PositiveRelationalValue",
                "positiveRelationalValue_invariant",
                "positiveValue_inv",
                "positiveRelationalValue_iff_hasStructuralWeight",
                "positiveRelationalValue_iff_normalized_pos",
                "V_welldef",
                "V_range",
                "V_endogenous",
                "weighted_O",
                "weighted_O_endogenous",
                "StableModel",
                "StableTarget",
                "countermodel",
                "HasStructuralWeight",
                "MatteringBridge",
            ],
            julia=[
                :viability_contribution,
                :viability_weight_ratio,
                :relational_normalized_value,
                :check_value_endogenous,
                :StableValueCountermodel,
                :stable_value_countermodel,
                :check_value_countermodel,
                :has_structural_weight,
                :MatteringBridge,
            ],
        ),
        (
            file="World.lean",
            lean=[
                "WorldFixedVector",
                "WldNontrivial",
                "Eeta",
                "Wld_band",
                "Fix",
                "band_invariant",
                "band_zero_eq_fix",
                "band_mono",
                "band_subset_Eeta",
                "worldLoop_def",
                "worldLoop_isSymmetric",
                "lambdaMax",
                "lambdaMax_hasEigenvalue",
                "lambdaMax_eq_normSq_T",
                "chi",
                "CriticalSlowingConjecture",
                "band_nontrivial_of_chi_le",
            ],
            julia=[
                :world_loop_operator,
                :WldResult,
                :world_nontrivial,
                :world_admissible,
                :world_band,
                :dominant_world_eigenvalue,
                :world_chi,
                :critical_slowing_score,
            ],
        ),
        (
            file="WorldDC.lean",
            lean=[
                "DCWorldBridge",
                "dc_and_world_of_bridge",
                "no_forward_unconditional",
                "no_backward_unconditional",
            ],
            julia=[
                :DCWorldBridge,
                :dc_world_bridge,
                :dc_world_harness,
                :check_no_unconditional_worlddc,
                :check_forward_worlddc_counterexample,
                :check_backward_worlddc_counterexample,
            ],
        ),
        (
            file="WorldDCRep.lean",
            lean=[
                "SensorimotorRepresentation",
                "IntertwiningRepresentation",
                "rep_fixed_of_intertwining",
                "wldNontrivial_of_intertwining",
            ],
            julia=Symbol[],
        ),
        (
            file="Graded.lean",
            lean=[
                "ThinCategory",
                "Presheaf",
                "FourPresheaves",
                "NaturalTransformation",
                "PresheafRelationFamily",
                "TransitionCoproduct",
                "PresheafTransitionCoproduct",
                "transitionOutputCopair_unique",
                "presheafTransition_naturality",
                "presheafTransitionOutputCopair_unique",
            ],
            julia=[
                :FiniteThinCategory,
                :GradedPresheaf,
                :FourPresheafSystem,
                :PresheafNaturalTransformation,
                :PresheafRelationFamily,
                :TransitionCoproduct,
                :PresheafTransitionCoproduct,
                :coproduct_copair,
                :check_presheaf_transition_naturality,
            ],
        ),
        (
            file="Decomp.lean",
            lean=["copair", "copair_unique", "canonical", "Reducible"],
            julia=[:copair, :check_copair_unique],
        ),
        (
            file="Grading.lean",
            lean=["WCat", "RelPresheaf", "AntitoneRelation", "constPresheaf_iff_antitone", "sieve", "w_crit", "sig2", "nuPhi_empty_above"],
            julia=[:check_const_presheaf_antitone, :check_sig2_collapse_bound],
        ),
        (
            file="Markers.lean",
            lean=[
                "FMMarkers",
                "FunctionalClass",
                "Conscious",
                "Blind",
                "conscious_classification",
                "blind_classification",
                "phiMinus",
                "FM1",
                "FM2",
                "staticInH",
                "FM3Frame",
                "FM3Iso",
                "FM3",
                "DynLabInvariantFamily",
                "FM4Frame",
                "FM4Iso",
                "FM4",
                "DynRepInvariantFamily",
                "FullMarkerFrame",
                "FullMarkerIso",
                "FullMarkerCoreIso",
                "FullMarkerCenterSymmetry",
                "FullMarkerFixedCenterSymmetry",
                "ConsciousAt",
                "BlindAt",
                "DynLabRepInvariantFamily",
                "andDynLabRepFamily",
                "orDynLabRepFamily",
                "notDynLabRepFamily",
                "impDynLabRepFamily",
                "iffDynLabRepFamily",
                "trueDynLabRepFamily",
                "falseDynLabRepFamily",
                "phiMinus_bisim",
                "fm1_invariant",
                "fm2_invariant",
                "staticInH_invariant",
                "fm3_invariant",
                "fm4_invariant",
                "consciousAt_invariant",
                "blindAt_invariant",
                "consciousAt_invariant_of_staticInH",
                "blindAt_invariant_of_staticInH",
                "dynLabRep_fixed_of_staticInH",
                "consciousAt_horizontal_wall_of_staticInH",
                "blindAt_horizontal_wall_of_staticInH",
                "fm1_inv",
                "fm2_inv",
                "fm3_inv",
                "fm4_inv",
                "consciousAt_inv",
                "blindAt_inv",
            ],
            julia=[:FMMarkers, :classify_action_markers],
        ),
        (
            file="OpenDynamics.lean",
            lean=[
                "EdgeKind",
                "OpenGraph",
                "Path",
                "Execution",
                "OpenFrame",
                "FiniteInternalHorizon",
                "Recoverable",
                "PossibleLive",
                "FairLive",
                "NoTerminalInit",
                "finiteInternalHorizon_not_recurrent",
            ],
            julia=[
                :OpenEdgeKind,
                :FiniteOpenGraph,
                :OpenPath,
                :FiniteOpenFrame,
                :check_finite_internal_horizon,
                :check_recoverable,
                :check_possible_live,
                :check_fair_lasso_live,
                :check_no_terminal_init,
            ],
        ),
        (
            file="Audit.lean",
            lean=[
                "Simulation",
                "CertifiedSimulation",
                "AuditMap",
                "noTerminalInit_sound",
                "GoalNI",
                "InternalFactor",
                "Certificate",
            ],
            julia=[
                :FiniteSimulation,
                :FiniteAuditMap,
                :check_no_terminal_audit_soundness,
                :check_goal_noninterference,
                :check_internal_factorization,
                :AuditCertificate,
            ],
        ),
        (
            file="Lineage.lean",
            lean=[
                "GenEvent",
                "SemanticEquivalence",
                "Lineage",
                "FreshSem",
                "EventuallyPeriodicSem",
                "Cofinal",
                "ProducesRicherSystem",
                "cofinal_implies_freshSem",
                "freshSem_not_eventuallyPeriodicSem",
            ],
            julia=[
                :FiniteSemanticEquivalence,
                :FiniteLineage,
                :check_fresh_sem_prefix,
                :check_eventually_periodic_sem_prefix,
                :check_cofinal_over_bounds,
                :check_produces_richer_system,
            ],
        ),
        (
            file="TheoryTranslation.lean",
            lean=[
                "Theory",
                "Translation",
                "SatisfactionPreserving",
                "Conservative",
                "GuaranteeProfile",
                "phenomenal_notCertified",
            ],
            julia=[
                :FiniteTheory,
                :FiniteTheoryTranslation,
                :check_satisfaction_preserving,
                :check_conservative_translation,
                :GuaranteeProfile,
            ],
        ),
        (
            file="Invariance.lean",
            declaration_files=[
                "Invariance/Basic.lean",
                "Invariance/Lemmas.lean",
                "Invariance/Static.lean",
                "Invariance/Dynamic.lean",
                "Invariance/Spectral.lean",
                "Invariance/External.lean",
            ],
            lean=[
                "StaticFrame",
                "KIso",
                "static_rel_bisim",
                "static_closure_bisim",
                "static_DC_bisim",
                "internal_bisim_kappa",
                "internal_bisim_epsilon",
                "DriftEquivariant",
                "upd_bisim",
                "iterate_bisim",
                "DynamicIso",
                "INS_invariant",
                "unitaryConjugate",
                "eigenspace_unitary",
                "wld_band_unitary",
                "eigenvalue_unitary",
                "unitary_conj",
                "E5",
            ],
            julia=[:check_update_bisimulation],
        ),
        (
            file="RefModel.lean",
            declaration_files=["RefModel/Basic.lean", "RefModel/Stable.lean", "RefModel/Dynamic.lean", "RefModel/Nondegenerate.lean", "RefModel/Richness.lean", "RefModel/Large.lean", "RefModel/LargeCore.lean", "RefModel/LineageWitness.lean"],
            lean=[
                "RefState", "next", "reference_models", "StableReferenceWitness",
                "stable_reference_model",
                "DynamicReferenceWitness", "dynamic_reference_model",
                "NondegenerateReferenceWitness", "nondegenerate_reference_model",
                "parameterizedRichDC", "parameterizedRichDC_act_eq_univ",
                "richImpl_hinge_card", "richImpl_realized_by_DC",
                "ParameterizedRichReferenceWitness", "parameterized_rich_reference_model",
                "largeFiniteDC", "LargeNondegenerateWitness",
                "arbitrarily_large_nondegenerate_dc",
                "LargeStableReferenceWitness", "LargeDynamicReferenceWitness",
                "LargeAXCoreReferenceWitness",
                "arbitrarily_large_ax_core_discrete_model",
                "LargeThreeLayerReferenceWitness",
                "arbitrarily_large_three_layer_reference_model",
                "richLineageDC", "richLineageDC_act_eq_univ",
                "richLineageDC_not_richnessWitness",
                "richLineageDC_phi_rich_eq_zero", "richLineageStep",
                "cardSem", "cardPhiRich", "richLineage",
                "cardPhiRich_score_richLineage",
                "richLineage_score_eq_hinge_card", "richLineage_cofinal",
                "RichLineageWitness", "rich_lineage_reference_model",
                "rich_lineage_freshSem",
                "rich_lineage_not_eventuallyPeriodic",
            ],
            julia=[
                :check_reference_models,
                :check_arbitrarily_large_nondegenerate_models,
                :check_arbitrarily_large_ax_core_discrete_models,
                :check_arbitrarily_large_three_layer_reference_models,
                :check_rich_lineage_cofinal,
            ],
        ),
        (
            file="Wager.lean",
            declaration_files=["Wager/Basic.lean", "Wager/Independence.lean", "Wager/Richness.lean", "Wager/Preservation.lean", "Wager/Models.lean"],
            lean=[
                "RawCore", "ConvHolds", "FrozenImpl", "W1", "W2", "W3", "W4", "W5", "W6",
                "W1_indep", "W2_indep", "W3_indep", "W4_indep", "W6_indep", "W5_indep_all",
                "definitional_extension_conservative", "W1_identification_conservative",
                "witness_pair_forward_stable",
                "WitnessPair", "PackPreserves", "ModelsAll",
                "global_frozen_protocol_invariant",
                "KBad", "M0", "KPlus", "MPlus", "MCyc",
                "named_frozen_models_boundary",
                "CycleAt", "W6_of_dc_cycle",
                "FrozenModelCheck", "frozen_model_checker_soundness",
                "FrozenInterpretiveCheck", "frozen_interpretive_checker_soundness",
                "FrozenFullModelCheck", "frozen_full_model_checker_soundness",
            ],
            julia=[:check_wager_independence, :check_w5_independence_family,
                :check_wager_conservative_extension,
                :check_frozen_protocol_invariant,
                :check_wager_named_models,
                :check_w6_cycle_soundness,
                :check_frozen_wager_interpretive_model,
                :check_frozen_wager_model,
                :check_frozen_wager_full_model],
        ),
        (
            file="Richness.lean",
            lean=[
                "Branch", "HingeBranchPump", "HingeBranchPumpWidth",
                "hinge_branch_pump", "hinge_branch_pump_width",
            ],
            julia=[:is_branch_point, :check_hinge_branch_pump],
        ),
        (
            file="Generation.lean",
            lean=[
                "dcToOpenSystem",
                "dcViable",
                "dcViableTranslation",
                "RichnessWitness",
                "phi_rich",
                "PhiRich",
                "ProliferationMorphism",
                "ProliferationMorphism.toGenerationWitness",
                "ProliferationEvent",
                "lineage_stays_open",
                "lineage_stays_open_phi_rich",
                "branch_transport_inherits_nu",
                "richness_inherits_generational",
            ],
            julia=[
                :check_dc_viable_translation,
                :check_proliferation_morphism,
                :check_lineage_stays_open,
                :check_richness_inherits_generational,
            ],
        ),
        (
            file="CertifiedArtifact.lean",
            lean=[
                "CertifiedContract",
                "CertifiedArtifact",
                "certifiedArtifact",
                "witness_presheafTransition_naturality",
            ],
            julia=[
                :CertifiedContract,
                :CertifiedArtifact,
                :parse_certified_artifact,
                :lean_certified_artifact,
                :verify_certified_artifact,
                :verify_lean_certified_artifact,
                :certified_artifact_ok,
                :julia_unverified_execution_boundary,
                :assert_julia_unverified_execution,
                :certificate_trust_profile,
                :certificate_dependency_graph,
                :certified_json_artifact_audit,
                :certified_json_artifact_audit_json,
                :dc_world_bridge_certificate,
                :presheaf_transition_certificate,
                :no_terminal_setpoint_certificate,
                :trm_rollout_dataset_certificate,
                :trm_linear_action_model_certificate,
                :trm_training_step_certificate,
                :trm_neural_action_model_certificate,
                :trm_neural_training_step_certificate,
                :trm_neural_training_run_certificate,
                :trm_neural_optimizer_state_certificate,
                :trm_neural_experiment_preset_catalog,
                :trm_neural_experiment_preset,
                :read_trm_neural_experiment_preset,
                :trm_neural_experiment_preset_certificate,
                :certified_trm_neural_experiment_preset,
                :certified_trm_neural_experiment_preset_json,
                :write_certified_trm_neural_experiment_preset,
                :run_trm_neural_training_experiment,
                :run_trm_neural_training_experiment_sweep,
                :trm_neural_experiment_sweep_report,
                :trm_neural_experiment_sweep_report_json,
                :write_trm_neural_experiment_sweep_report,
                :trm_neural_experiment_sweep_report_certificate,
                :certified_trm_neural_experiment_sweep_report,
                :certified_trm_neural_experiment_sweep_report_json,
                :write_certified_trm_neural_experiment_sweep_report,
                :trm_neural_experiment_sweep_certificate_graph,
                :trm_neural_experiment_sweep_certificate_graph_json,
                :write_trm_neural_experiment_sweep_certificate_graph,
                :trm_neural_experiment_sweep_certified_envelope_audit,
                :trm_neural_experiment_sweep_certified_envelope_audit_json,
                :write_trm_neural_experiment_sweep_certified_envelope_audit,
                :write_trm_neural_optimizer_state_tsv,
                :read_trm_neural_optimizer_state_tsv,
                :trm_neural_optimizer_checkpoint_certificate,
                :certified_trm_neural_optimizer_checkpoint,
                :lenia_architecture_status_certificate,
                :lenia_tau_sweep_certificate,
                :lenia_feature_sweep_certificate,
                :lenia_parameter_grid_certificate,
            ],
        ),
    ]

    declaration_regex(name) =
        Regex("(?m)^(?:noncomputable\\s+)?(structure|def|theorem|inductive|abbrev)\\s+$name\\b")

    exported = Set(names(ERIEC))
    for contract in contracts
        declaration_files = hasproperty(contract, :declaration_files) ?
            contract.declaration_files : [contract.file]
        texts = read.(joinpath.(formal_root, declaration_files), String)
        for lean_name in contract.lean
            @test any(text -> occursin(declaration_regex(lean_name), text), texts)
        end
        for julia_name in contract.julia
            @test julia_name in exported
            @test isdefined(ERIEC, julia_name)
        end
    end

    artifact_text = cd(project_root) do
        read(`lake env lean --run formal/ERIEC/CertifiedArtifact.lean`, String)
    end
    artifact = parse_certified_artifact(artifact_text)
    @test artifact.version == 1
    @test artifact.artifact_id == "erie-c-certified-boundary"
    @test certified_artifact_contract_ids(artifact) == [
        "adjunction.system",
        "adjunction.rigidity",
        "interface.relation_linearization",
        "interface.sensitivity_realization",
        "interface.relation_naturality",
        "interface.relation_lax_naturality",
        "interface.strict_naturality_counterexample",
        "bridge.alpha_only_counterexample",
        "bridge.raw_gram_counterexample",
        "bridge.hinge_object_classifier",
        "bridge.hinge_lax_map",
        "bridge.hinge_thin_functor",
        "bridge.hinge_strict_functor",
        "bridge.hinge_hilbert_functor",
        "bridge.hinge_structural_functor",
        "viability.closure_object",
        "viability.closure_functor",
        "viability.relational_frame",
        "viability.relational_functor",
        "layers.viable_to_hilbert",
        "layers.nonfaithful_counterexample",
        "grading.const_presheaf_antitone",
        "grading.critical_rank",
        "closure.nu_phi",
        "closure.knaster_tarski",
        "hinge.act",
        "collapse.critical_slowing",
        "dynamics.finite_collapse",
        "dc.system",
        "certification.critical_bound",
        "sensitivity.dual_symmetry",
        "sensitivity.no_order_unit",
        "world.spectral_band",
        "value.endogenous",
        "world.actuated",
        "worlddc.bridge",
        "worlddc.no_unconditional_equivalence",
        "worlddc.representation.forward",
        "graded.presheaf_transition_coproduct",
        "decomp.copair_unique",
        "graded.presheaf_transition_naturality",
        "graded.presheaf_transition_output_copair_unique",
        "body.no_terminal_setpoint",
        "guard.terminal_iff",
        "markers.fm_classification",
        "opendynamics.open_graph",
        "audit.simulation",
        "audit.certified_simulation",
        "lineage.core",
        "theorytr.phenomenal_guard",
        "invariance.update_bisimulation",
        "reference_models.v5_1",
        "reference_models.stable_v2",
        "reference_models.dynamic_v2",
        "reference_models.nondegenerate_v2",
        "reference_models.arbitrarily_large_dc",
        "reference_models.arbitrarily_large_ax_core_discrete",
        "reference_models.arbitrarily_large_three_layer",
        "wager.frozen_independence",
        "wager.w5_independence_family",
        "wager.conservative_extension",
        "wager.global_protocol_invariant",
        "wager.named_models",
        "wager.w6_cycle_soundness",
        "wager.interpretive_model_checker",
        "wager.finite_model_checker",
        "wager.full_model_checker",
        "richness.branch",
        "richness.hinge_branch_pump",
        "generation.dc_viable_translation",
        "generation.proliferation_morphism",
        "generation.lineage_stays_open",
        "generation.richness_inherits_generational",
        "generation.rich_lineage_cofinal",
        "v52.gate.propagation",
        "v52.gate.soundness",
        "v52.gate.unique",
        "v52.gap.branch",
        "v52.gap.degeneracy",
        "v52.gap.trichotomy",
        "v52.decay.psi",
        "v52.decay.abstract_collapse",
        "v52.decay.collapse_of_psi",
        "v52.decay.psi2",
        "v52.opensimc.identity_audit",
        "v52.opensimc.path_units",
        "v52.opensimc.erase_functor",
        "v52.kernelopen.action_gap",
        "v52.centering.horizontal_wall",
        "v52.centering.fixed_specialization",
        "v52.centering.strength_data",
        "v52.centering.quantified_closure",
        "v52.value.positive_static_invariant",
        "v52.markers.fm1_static_invariant",
        "v52.markers.fm2_static_invariant",
        "v52.markers.static_hinge_invariant",
        "v52.markers.fm3_dynlab_invariant",
        "v52.markers.fm4_dynrep_invariant",
        "v52.markers.conscious_dynlabrep_invariant",
        "v52.markers.blind_dynlabrep_invariant",
        "v52.markers.conscious_static_hinge_dynlabrep_invariant",
        "v52.markers.blind_static_hinge_dynlabrep_invariant",
        "v52.markers.dynlabrep_static_hinge_fixed_specialization",
        "v52.markers.conscious_static_hinge_horizontal_wall",
        "v52.markers.blind_static_hinge_horizontal_wall",
        "v52.analyticfm4.coordinate_swap_unitary",
        "v52.analyticfm4.eigenspace_transport",
        "v52.analyticfm4.hilbert_unitary_invariant",
        "v52.analyticfm4.complex_hilbert_unitary_invariant",
        "v52.analyticfm4.complex_full_marker_link",
        "v52.traceability.vocabulary",
        "v52.traceability.soundness",
        "v52.refmodel.symmetric_double",
        "v52.refmodel.recurrent_gate_viability",
        "v52.refmodel.standard_gate_profile",
        "v52.refmodel.symmetric_double_positive_value",
        "v52.refmodel.symmetric_double_full_marker",
        "v52.refmodel.symmetric_double_analytic_fm4",
        "v52.refmodel.symmetric_double_euclidean_hilbert_fm4",
        "v52.refmodel.symmetric_double_complex_hilbert_fm4",
        "v52.refmodel.symmetric_double_complex_full_marker",
        "v52.refmodel.symmetric_double_three_stage_dynamics",
        "v52.refmodel.symmetric_double_obs_lab_exchange",
        "v52.refmodel.symmetric_double_converse_relations",
        "v52.refmodel.symmetric_double_orthogonal_projection",
        "v52.refmodel.symmetric_double_dynamic_conjugacy",
        "v52.refmodel.symmetric_double_dynamic_orbit_invariance",
        "v52.markers.analytic_fm4_unitary",
        "v52.refmodel.analytic_symmetric_double",
        "v52.refmodel.full_marker_analytic_fm4",
        "v52.refmodel.symmetric_double_dynamics",
        "v52.refmodel.symmetric_double_dynamic_iso",
        "v52.refmodel.symmetric_double_update_bisim",
        "v52.refmodel.symmetric_double_full_witness",
        "v52.refmodel.full_marker_conscious_wall",
        "v52.refmodel.full_marker_blind_wall",
        "v52.refmodel.symmetric_double_blind",
        "v52.refmodel.symmetric_double_not_conscious",
        "v52.refmodel.symmetric_double_fm1",
        "v52.refmodel.noniso_multiplicity",
        "v52.refmodel.nondegenerate_recur_full",
        "v52.refmodel.nondegenerate_recur_integrated",
        "v52.refmodel.horizontal_wall_witness",
    ]

    artifact_check = verify_certified_artifact(artifact; project_root=project_root)
    @test certified_artifact_ok(artifact_check)
    @test isempty(artifact_check.missing_imports)
    @test isempty(artifact_check.missing_lean)
    @test isempty(artifact_check.missing_julia)
    @test isempty(artifact_check.missing_checkers)
    v52_contracts = filter(contract -> startswith(contract.id, "v52."), artifact.contracts)
    @test length(v52_contracts) == 69
    @test all(contract -> contract.julia_symbol === nothing, v52_contracts)
    @test all(contract -> contract.julia_checker === nothing, v52_contracts)

    summary = certification_summary(artifact_check)
    @test summary.ok
    @test summary.schema_version == 1
    @test summary.artifact_id == artifact.artifact_id
    @test summary.contracts == certified_artifact_contract_ids(artifact)
    @test any(
        detail.id == "graded.presheaf_transition_output_copair_unique" &&
            detail.lean_name == "presheafTransitionOutputCopair_unique"
        for detail in summary.contract_details
    )
    @test any(
        detail.id == "worlddc.representation.forward" &&
            detail.lean_module == "ERIEC.WorldDCRep" &&
            detail.julia_symbol === nothing &&
            detail.julia_checker === nothing
        for detail in summary.contract_details
    )

    envelope = certified_artifact_envelope((kind=:smoke,), artifact_check)
    @test envelope.payload.kind == :smoke
    @test envelope.certificate.ok
    @test !envelope.trust.formally_certified
    @test !envelope.trust.runtime_checked
    @test envelope.trust.execution_layer == :unspecified
    @test !envelope.trust.execution_certified
    @test envelope.trust.execution_boundary == :unspecified
    @test envelope.trust.boundary == :lean_core_julia_shell
    @test julia_unverified_execution_boundary().execution_layer == :julia_unverified
    @test julia_unverified_execution_boundary().execution_certified == false
    @test assert_julia_unverified_execution(julia_unverified_execution_boundary())
    @test_throws ArgumentError assert_julia_unverified_execution((
        execution_layer=:julia_unverified,
        execution_certified=true,
    ))
    @test envelope.certificate.contracts == certified_artifact_contract_ids(artifact)
    @test_throws ArgumentError certified_artifact_envelope(
        (
            kind=:bad,
            lean_contracts=["missing.contract"],
            julia_checkers=Symbol[],
            numeric_assumptions=NamedTuple(),
        ),
        artifact_check,
    )

    graph_envelope = certified_artifact_envelope(
        (
            kind=:smoke,
            lean_contracts=["worlddc.bridge"],
            julia_checkers=[:check_worlddc_bridge],
            numeric_assumptions=NamedTuple(),
        ),
        artifact_check,
    )
    graph = certificate_dependency_graph(graph_envelope)
    @test graph.trust.formally_certified
    @test graph.trust.runtime_checked
    @test !graph.trust.execution_certified
    @test any(
        dependency.contract == "worlddc.bridge" &&
            dependency.lean_module == "ERIEC.WorldDC" &&
            dependency.declaration == "DCWorldBridge"
        for dependency in graph.lean_dependencies
    )
    @test any(edge.relation == :lean_dependency for edge in graph.edges)

    rich_lineage_envelope = certified_artifact_envelope(
        (
            kind=:rich_lineage,
            lean_contracts=["generation.rich_lineage_cofinal"],
            julia_checkers=[:check_rich_lineage_cofinal],
            numeric_assumptions=NamedTuple(),
        ),
        artifact_check,
    )
    rich_lineage_graph = certificate_dependency_graph(rich_lineage_envelope)
    @test any(
        dependency.contract == "generation.rich_lineage_cofinal" &&
            dependency.lean_module == "ERIEC.RefModel.LineageWitness" &&
            dependency.declaration == "rich_lineage_reference_model"
        for dependency in rich_lineage_graph.lean_dependencies
    )
    @test any(
        edge.from == "generation.rich_lineage_cofinal" &&
            edge.to == "ERIEC.RefModel.LineageWitness.rich_lineage_reference_model" &&
            edge.relation == :lean_dependency
        for edge in rich_lineage_graph.edges
    )
end
