import Mathlib.CategoryTheory.Category.Basic
import ERIEC.TemporalDC

namespace ERIEC

namespace OpenDynamics

universe u v w

/-- §17.1: an edge is either internal or crosses a typed coupling port. -/
inductive EdgeKind (Port : Type u) where
  | internal
  | coupling (port : Port)
  deriving DecidableEq

/-- §17.1: a typed, labelled open transition graph. -/
structure OpenGraph (Port : Type u) where
  State : Type v
  step : State → EdgeKind Port → State → Prop

/-- §17.2: the free, endpoint-indexed paths generated by an open graph. -/
inductive Path {Port : Type u} (G : OpenGraph.{u, v} Port) :
    G.State → G.State → Type (max u v) where
  | nil (s : G.State) : Path G s s
  | cons {s m t : G.State} {kind : EdgeKind Port} :
      G.step s kind m → Path G m t → Path G s t

namespace Path

variable {Port : Type u} {G : OpenGraph.{u, v} Port}

/-- Concatenation is composition in the free path category. -/
def append : {r s t : G.State} → Path G r s → Path G s t → Path G r t
  | _, _, _, .nil _, q => q
  | _, _, _, .cons edge p, q => .cons edge (append p q)

@[simp] theorem nil_append {r s : G.State} (p : Path G r s) :
    append (.nil r) p = p :=
  rfl

@[simp] theorem append_nil {r s : G.State} (p : Path G r s) :
    append p (.nil s) = p := by
  induction p with
  | nil => rfl
  | cons edge p ih => simp [append, ih]

theorem append_assoc {r s t z : G.State}
    (p : Path G r s) (q : Path G s t) (h : Path G t z) :
    append (append p q) h = append p (append q h) := by
  induction p with
  | nil => rfl
  | cons edge p ih => simp [append, ih]

/-- Number of generating edges in a path. -/
def length : {r s : G.State} → Path G r s → Nat
  | _, _, .nil _ => 0
  | _, _, .cons _ p => length p + 1

@[simp] theorem length_nil {r : G.State} : length (.nil r : Path G r r) = 0 :=
  rfl

@[simp] theorem length_cons {r s t : G.State} {kind : EdgeKind Port}
    (edge : G.step r kind s)
    (p : Path G s t) : length (.cons edge p) = p.length + 1 :=
  rfl

@[simp] theorem length_append {r s t : G.State}
    (p : Path G r s) (q : Path G s t) :
    length (append p q) = length p + length q := by
  induction p with
  | nil => simp [append]
  | cons edge p ih => simp [append, ih, Nat.add_assoc, Nat.add_comm]

/-- All generating edges of the path are internal. -/
def Internal : {r s : G.State} → Path G r s → Prop
  | _, _, .nil _ => True
  | _, _, .cons (kind := kind) _ p => kind = .internal ∧ Internal p

@[simp] theorem internal_nil {r : G.State} : Internal (.nil r : Path G r r) :=
  trivial

theorem internal_append {r s t : G.State} {p : Path G r s} {q : Path G s t}
    (hp : p.Internal) (hq : q.Internal) : (append p q).Internal := by
  induction p with
  | nil => exact hq
  | @cons _ _ _ kind edge p ih =>
      exact ⟨hp.1, ih hp.2 hq⟩

@[simp] theorem length_cast_right {r s t : G.State} (h : s = t)
    (p : Path G r s) : length (h ▸ p) = length p := by
  subst h
  rfl

@[simp] theorem internal_cast_right {r s t : G.State} (h : s = t)
    (p : Path G r s) : Internal (h ▸ p) ↔ Internal p := by
  subst h
  rfl

def castSource {r r' s : G.State} (h : r = r')
    (p : Path G r s) : Path G r' s :=
  h ▸ p

def castTarget {r s s' : G.State} (h : s = s')
    (p : Path G r s) : Path G r s' :=
  h ▸ p

@[simp] theorem length_castSource {r r' s : G.State} (h : r = r')
    (p : Path G r s) : (castSource h p).length = p.length := by
  subst h
  rfl

@[simp] theorem length_castTarget {r s s' : G.State} (h : s = s')
    (p : Path G r s) : (castTarget h p).length = p.length := by
  subst h
  rfl

/-- A single graph edge as a free path. -/
def single {r s : G.State} {kind : EdgeKind Port}
    (edge : G.step r kind s) : Path G r s :=
  .cons edge (.nil s)

end Path

/-- §17.3: states and labelled edges of one infinite execution. -/
structure Execution {Port : Type u} (G : OpenGraph.{u, v} Port) where
  state : Nat → G.State
  kind : Nat → EdgeKind Port
  edge : ∀ n, G.step (state n) (kind n) (state (n + 1))

namespace Execution

variable {Port : Type u} {G : OpenGraph.{u, v} Port}

/-- The length-`d` segment beginning at execution time `n`. -/
def segment (x : Execution G) (n : Nat) :
    (d : Nat) → Path G (x.state n) (x.state (n + d))
  | 0 => .nil (x.state n)
  | d + 1 => Path.append (segment x n d) (Path.single (x.edge (n + d)))

@[simp] theorem segment_length (x : Execution G) (n d : Nat) :
    (x.segment n d).length = d := by
  induction d generalizing n with
  | zero => rfl
  | succ d ih =>
      simp [segment, ih, Path.single]

/-- §17.5: a pure internal execution uses no coupling edge. -/
def PureInternal (x : Execution G) : Prop :=
  ∀ n, x.kind n = .internal

theorem segment_internal (x : Execution G) (hx : x.PureInternal) (n d : Nat) :
    (x.segment n d).Internal := by
  induction d generalizing n with
  | zero => trivial
  | succ d ih =>
      apply Path.internal_append (ih (n := n))
      exact ⟨hx (n + d), trivial⟩

end Execution

/-- §17.4: an open frame with an explicitly inhabited recovery envelope. -/
structure OpenFrame (Port : Type u) where
  graph : OpenGraph.{u, v} Port
  init : graph.State → Prop
  admissible : graph.State → Prop
  envelope : graph.State → Prop
  admissible_subset_envelope : ∀ {s}, admissible s → envelope s
  fair : Execution graph → Prop

namespace OpenFrame

variable {Port : Type u} (O : OpenFrame.{u, v} Port)

abbrev State := O.graph.State

/-- §17.6: every sufficiently long internal path from an admissible state
leaves the admissible region. -/
def FiniteInternalHorizon : Prop :=
  ∀ s, O.admissible s → ∃ N,
    ∀ t (p : Path O.graph s t),
      p.Internal → N ≤ p.length → ¬ O.admissible t

def InternalTotal : Prop :=
  ∀ s, ∃ t, O.graph.step s .internal t

/-- §17.7: infinitely many returns to the admissible region. -/
def Recurrent (x : Execution O.graph) : Prop :=
  ∀ n, ∃ m, n ≤ m ∧ O.admissible (x.state m)

def BoundedRecurrent (bound : Nat) (x : Execution O.graph) : Prop :=
  ∀ n, ∃ m, n ≤ m ∧ m ≤ n + bound ∧ O.admissible (x.state m)

theorem boundedRecurrent_recurrent {bound : Nat} {x : Execution O.graph}
    (h : O.BoundedRecurrent bound x) : O.Recurrent x := by
  intro n
  obtain ⟨m, hnm, _, hm⟩ := h n
  exact ⟨m, hnm, hm⟩

/-- §17.8: existential/open-system liveness. -/
def PossibleLive : Prop :=
  ∃ x : Execution O.graph, O.init (x.state 0) ∧ O.Recurrent x

/-- The explicit realizability premise prevents vacuous fair liveness. -/
def FairRealizable : Prop :=
  ∀ s, O.init s → ∃ x : Execution O.graph, x.state 0 = s ∧ O.fair x

def FairLive : Prop :=
  O.FairRealizable ∧
    ∀ x : Execution O.graph,
      O.init (x.state 0) → O.fair x → O.Recurrent x

def BoundedLive (bound : Nat) : Prop :=
  O.FairRealizable ∧
    ∀ x : Execution O.graph,
      O.init (x.state 0) → O.fair x → O.BoundedRecurrent bound x

theorem boundedLive_fairLive {bound : Nat} (h : O.BoundedLive bound) :
    O.FairLive := by
  refine ⟨h.1, ?_⟩
  intro x hx hfair
  exact O.boundedRecurrent_recurrent (h.2 x hx hfair)

/-- §17.9: every state in the recovery envelope has a path back to `A`. -/
def Recoverable : Prop :=
  ∀ s, O.envelope s → ∃ t, O.admissible t ∧ Nonempty (Path O.graph s t)

def RecoverableWithin (bound : Nat) : Prop :=
  ∀ s, O.envelope s → ∃ t, ∃ p : Path O.graph s t,
    O.admissible t ∧ Path.length p ≤ bound

def Down (s : O.State) : Prop :=
  ∃ t, O.admissible t ∧ Nonempty (Path O.graph s t)

def Irreversible (s : O.State) : Prop :=
  ¬ O.Down s

/-- Theorem 17.10: the irreversible region is forward closed. -/
theorem irreversible_forward_closed {s t : O.State} {kind : EdgeKind Port}
    (hs : O.Irreversible s) (edge : O.graph.step s kind t) :
    O.Irreversible t := by
  intro ht
  obtain ⟨a, ha, ⟨path⟩⟩ := ht
  exact hs ⟨a, ha, ⟨Path.cons edge path⟩⟩

/-- Theorem 17.11: FIH excludes recurrence of every pure-internal execution. -/
theorem finiteInternalHorizon_not_recurrent
    (hfih : O.FiniteInternalHorizon)
    (x : Execution O.graph)
    (hpure : x.PureInternal) :
    ¬ O.Recurrent x := by
  intro hrecur
  obtain ⟨start, _, hstart⟩ := hrecur 0
  obtain ⟨N, hN⟩ := hfih (x.state start) hstart
  obtain ⟨finish, hfinish, hAfinish⟩ := hrecur (start + N)
  let d := finish - start
  have hsd : start + d = finish := Nat.add_sub_of_le (le_trans (Nat.le_add_right start N) hfinish)
  have hNd : N ≤ d := by omega
  let p0 := x.segment start d
  have hpInternal0 : p0.Internal := x.segment_internal hpure start d
  have hpLength0 : p0.length = d := x.segment_length start d
  have stateEq : x.state (start + d) = x.state finish := congrArg x.state hsd
  let p : Path O.graph (x.state start) (x.state finish) := stateEq ▸ p0
  have hpInternal : p.Internal := by
    simpa [p] using hpInternal0
  have hpLength : p.length = d := by
    simpa [p] using hpLength0
  exact hN (x.state finish) p hpInternal (hpLength.symm ▸ hNd) hAfinish

/-- §17.13: reachability from the declared initial region. -/
def ReachInit (t : O.State) : Prop :=
  ∃ s, O.init s ∧ Nonempty (Path O.graph s t)

def HasTerminalInit : Prop :=
  ∃ t, O.ReachInit t ∧ ∀ s, O.ReachInit s → Nonempty (Path O.graph s t)

def NoTerminalInit : Prop :=
  ¬ O.HasTerminalInit

/-- §17.14: periodicity includes both states and provenance labels. -/
def EventuallyPeriodic (x : Execution O.graph) : Prop :=
  ∃ N p, 0 < p ∧ ∀ n, N ≤ n →
    x.state (n + p) = x.state n ∧ x.kind (n + p) = x.kind n

def Aperiodic (x : Execution O.graph) : Prop :=
  ¬ O.EventuallyPeriodic x

def FreshState (x : Execution O.graph) : Prop :=
  ∀ n, ∃ m, n ≤ m ∧ ∀ k, k < m → x.state m ≠ x.state k

end OpenFrame

/-! Theorem 17.3: the endpoint-indexed paths form the free path category. -/

section FreePathCategory

open CategoryTheory

variable {Port : Type u} (G : OpenGraph.{u, v} Port)

instance freePathCategory : CategoryTheory.Category G.State where
  Hom := Path G
  id := Path.nil
  comp := Path.append
  id_comp := Path.nil_append
  comp_id := Path.append_nil
  assoc := Path.append_assoc

end FreePathCategory

/-- Objects of the internal-edge free-path subcategory. A wrapper is used so
the ambient and internal category instances cannot conflict. -/
structure InternalObject {Port : Type u} (G : OpenGraph.{u, v} Port) where
  state : G.State

namespace InternalObject

open CategoryTheory

variable {Port : Type u} (G : OpenGraph.{u, v} Port)

instance internalFreePathCategory : CategoryTheory.Category (InternalObject G) where
  Hom := fun source target =>
    {path : Path G source.state target.state // path.Internal}
  id := fun object => ⟨.nil object.state, trivial⟩
  comp := fun left right =>
    ⟨left.1.append right.1, Path.internal_append left.2 right.2⟩
  id_comp := by
    intro source target morphism
    apply Subtype.ext
    exact Path.nil_append morphism.1
  comp_id := by
    intro source target morphism
    apply Subtype.ext
    exact Path.append_nil morphism.1
  assoc := by
    intro first second third fourth f g h
    apply Subtype.ext
    exact Path.append_assoc f.1 g.1 h.1

end InternalObject

/-! Finite witnesses from Theorem 17.12. -/

namespace ReferenceModels

inductive TwoState where
  | a
  | b
  deriving DecidableEq, Repr

open TwoState

/-- The graph shared by `M_recur` and its fair refinements. -/
def recurGraph : OpenGraph Unit where
  State := TwoState
  step
    | .a, .internal, .b => True
    | .b, .internal, .b => True
    | .b, .coupling (), .a => True
    | _, _, _ => False

def recurFrame : OpenFrame Unit where
  graph := recurGraph
  init := (· = .a)
  admissible := (· = .a)
  envelope := fun _ => True
  admissible_subset_envelope := by simp
  fair := fun _ => True

private theorem recur_internal_edge_target_b {s t : TwoState}
    (edge : recurGraph.step s .internal t) : t = .b := by
  cases s <;> cases t <;> simp [recurGraph] at edge ⊢

private def recur_internal_from_b_target_b :
    {s t : TwoState} → (p : Path recurGraph s t) →
      s = .b → p.Internal → t = .b
  | _, _, .nil _, hs, _ => hs
  | _, _, .cons (kind := kind) edge rest, _, hp => by
      have hkind : kind = EdgeKind.internal := hp.1
      subst kind
      exact recur_internal_from_b_target_b rest
        (recur_internal_edge_target_b edge) hp.2

private theorem recur_internal_nonempty_target_b {s t : TwoState}
    (p : Path recurGraph s t) (hp : p.Internal) (hlen : 1 ≤ p.length) :
    t = .b :=
  match p with
  | .nil _ => by simp at hlen
  | .cons (kind := kind) edge rest => by
      have hkind : kind = EdgeKind.internal := hp.1
      subst kind
      exact recur_internal_from_b_target_b rest
        (recur_internal_edge_target_b edge) hp.2

/-- `M_recur` has internal horizon one. -/
theorem recur_finiteInternalHorizon : recurFrame.FiniteInternalHorizon := by
  intro s hs
  refine ⟨1, ?_⟩
  intro t p hp hlen ht
  have htB := recur_internal_nonempty_target_b p hp hlen
  change t = TwoState.a at ht
  exact TwoState.noConfusion (htB.symm.trans ht)

/-- Every state of `M_recur` can return to `A`; the `b` return uses coupling. -/
theorem recur_recoverable : recurFrame.Recoverable := by
  intro s _
  cases s with
  | a =>
      refine ⟨TwoState.a, rfl, ⟨?_⟩⟩
      simpa [recurFrame] using
        (@Path.nil Unit recurGraph TwoState.a)
  | b =>
      refine ⟨TwoState.a, rfl, ⟨?_⟩⟩
      have edge : recurGraph.step TwoState.b (.coupling ()) TwoState.a := trivial
      simpa [recurFrame] using Path.single edge

def alternatingState : Nat → TwoState
  | 0 => .a
  | n + 1 => match alternatingState n with
    | .a => .b
    | .b => .a

def alternatingKind (n : Nat) : EdgeKind Unit :=
  match alternatingState n with
  | .a => .internal
  | .b => .coupling ()

def alternatingExecution : Execution recurGraph where
  state := alternatingState
  kind := alternatingKind
  edge := by
    intro n
    cases h : alternatingState n <;>
      simp [alternatingKind, alternatingState, h, recurGraph]

theorem alternating_recurrent : recurFrame.Recurrent alternatingExecution := by
  intro n
  cases h : alternatingState n with
  | a => exact ⟨n, le_rfl, h⟩
  | b =>
      refine ⟨n + 1, by omega, ?_⟩
      change alternatingState (n + 1) = TwoState.a
      simp [alternatingState, h]

theorem recur_possibleLive : recurFrame.PossibleLive :=
  ⟨alternatingExecution, rfl, alternating_recurrent⟩

/-- Theorem 17.12 compatibility witness: finite internal horizon and open
recurrence hold simultaneously. -/
theorem finiteInternalHorizon_and_possibleLive :
    recurFrame.FiniteInternalHorizon ∧ recurFrame.PossibleLive :=
  ⟨recur_finiteInternalHorizon, recur_possibleLive⟩

/-- An unfair scheduler can enter `b` and take internal self-loops forever. -/
def stalledExecution : Execution recurGraph where
  state
    | 0 => .a
    | _ + 1 => .b
  kind := fun _ => .internal
  edge := by
    intro n
    cases n <;> simp [recurGraph]

theorem stalled_not_recurrent : ¬ recurFrame.Recurrent stalledExecution := by
  intro h
  obtain ⟨m, hm, hA⟩ := h 1
  cases m with
  | zero => omega
  | succ m =>
      change TwoState.b = TwoState.a at hA
      exact TwoState.noConfusion hA

/-- `PossibleLive` does not imply `FairLive` when fairness is `True`. -/
theorem recur_not_fairLive : ¬ recurFrame.FairLive := by
  intro h
  exact stalled_not_recurrent (h.2 stalledExecution rfl trivial)

theorem possibleLive_not_imply_fairLive :
    recurFrame.PossibleLive ∧ ¬ recurFrame.FairLive :=
  ⟨recur_possibleLive, recur_not_fairLive⟩

/-- `M_fair`: whenever the execution is at `b`, the scheduler immediately
chooses the typed repair coupling. -/
def fairFrame : OpenFrame Unit where
  graph := recurGraph
  init := (· = .a)
  admissible := (· = .a)
  envelope := fun _ => True
  admissible_subset_envelope := by simp
  fair := fun x => ∀ n, x.state n = .b → x.kind n = .coupling ()

theorem alternating_fair : fairFrame.fair alternatingExecution := by
  intro n hn
  change alternatingState n = TwoState.b at hn
  simp [alternatingExecution, alternatingKind, hn]

theorem fairFrame_realizable : fairFrame.FairRealizable := by
  intro s hs
  change s = TwoState.a at hs
  subst s
  exact ⟨alternatingExecution, rfl, alternating_fair⟩

private theorem recur_coupling_edge_target_a {s t : TwoState}
    (edge : recurGraph.step s (.coupling ()) t) : t = .a := by
  cases s <;> cases t <;> simp [recurGraph] at edge ⊢

theorem fairFrame_boundedLive_one : fairFrame.BoundedLive 1 := by
  refine ⟨fairFrame_realizable, ?_⟩
  intro x _ hfair n
  cases hn : x.state n with
  | a => exact ⟨n, le_rfl, by omega, hn⟩
  | b =>
      refine ⟨n + 1, by omega, by omega, ?_⟩
      have hkind := hfair n hn
      have edge := x.edge n
      change recurGraph.step (x.state n) (x.kind n) (x.state (n + 1)) at edge
      rw [hn, hkind] at edge
      exact recur_coupling_edge_target_a edge

theorem fairFrame_fairLive : fairFrame.FairLive :=
  fairFrame.boundedLive_fairLive fairFrame_boundedLive_one

/-- `M_fall`: the same internal collapse graph with no repair coupling. -/
def fallGraph : OpenGraph Unit where
  State := TwoState
  step
    | .a, .internal, .b => True
    | .b, .internal, .b => True
    | _, _, _ => False

def fallFrame : OpenFrame Unit where
  graph := fallGraph
  init := (· = .a)
  admissible := (· = .a)
  envelope := (· = .a)
  admissible_subset_envelope := fun h => h
  fair := fun _ => True

private theorem fall_internal_edge_target_b {s t : TwoState}
    (edge : fallGraph.step s .internal t) : t = .b := by
  cases s <;> cases t <;> simp [fallGraph] at edge ⊢

private def fall_internal_from_b_target_b :
    {s t : TwoState} → (p : Path fallGraph s t) →
      s = .b → p.Internal → t = .b
  | _, _, .nil _, hs, _ => hs
  | _, _, .cons (kind := kind) edge rest, _, hp => by
      have hkind : kind = EdgeKind.internal := hp.1
      subst kind
      exact fall_internal_from_b_target_b rest
        (fall_internal_edge_target_b edge) hp.2

private theorem fall_internal_nonempty_target_b {s t : TwoState}
    (p : Path fallGraph s t) (hp : p.Internal) (hlen : 1 ≤ p.length) :
    t = .b :=
  match p with
  | .nil _ => by simp at hlen
  | .cons (kind := kind) edge rest => by
      have hkind : kind = EdgeKind.internal := hp.1
      subst kind
      exact fall_internal_from_b_target_b rest
        (fall_internal_edge_target_b edge) hp.2

theorem fall_finiteInternalHorizon : fallFrame.FiniteInternalHorizon := by
  intro s hs
  refine ⟨1, ?_⟩
  intro t p hp hlen ht
  have htB := fall_internal_nonempty_target_b p hp hlen
  change t = TwoState.a at ht
  exact TwoState.noConfusion (htB.symm.trans ht)

theorem fall_execution_pureInternal (x : Execution fallGraph) : x.PureInternal := by
  intro n
  have edge := x.edge n
  cases hkind : x.kind n with
  | internal => rfl
  | coupling port =>
      cases port
      rw [hkind] at edge
      change fallGraph.step (x.state n) (.coupling ()) (x.state (n + 1)) at edge
      cases hs : x.state n <;> cases ht : x.state (n + 1) <;>
        simp [fallGraph, hs, ht] at edge

theorem fall_not_possibleLive : ¬ fallFrame.PossibleLive := by
  rintro ⟨x, _, hrecurrent⟩
  exact fallFrame.finiteInternalHorizon_not_recurrent
    fall_finiteInternalHorizon x (fall_execution_pureInternal x) hrecurrent

/-- FIH alone does not imply open recurrence. -/
theorem finiteInternalHorizon_not_imply_possibleLive :
    fallFrame.FiniteInternalHorizon ∧ ¬ fallFrame.PossibleLive :=
  ⟨fall_finiteInternalHorizon, fall_not_possibleLive⟩

/-- The final nonimplication of Theorem 17.15, witnessed without enlarging the
two-state model. -/
theorem possibleLive_not_imply_freshState :
    recurFrame.PossibleLive ∧
      ¬ ∃ x : Execution recurFrame.graph,
        recurFrame.init (x.state 0) ∧ recurFrame.FreshState x := by
  refine ⟨recur_possibleLive, ?_⟩
  rintro ⟨x, hxInit, hxFresh⟩
  -- Freshness is impossible for every execution over the two-state carrier:
  -- at any index at least two, its value repeats either index zero or index one.
  have h0 : x.state 0 = TwoState.a := hxInit
  have h1 : x.state 1 = TwoState.b := by
    have edge := x.edge 0
    change recurGraph.step (x.state 0) (x.kind 0) (x.state 1) at edge
    rw [h0] at edge
    cases x.kind 0 with
    | internal =>
        cases hstate : x.state 1 with
        | a => simp [recurGraph, hstate] at edge
        | b => rfl
    | coupling port =>
        cases port
        cases hstate : x.state 1 with
        | a => simp [recurGraph, hstate] at edge
        | b => rfl
  obtain ⟨m, hm, hnew⟩ := hxFresh 2
  cases hmstate : x.state m with
  | a => exact hnew 0 (by omega) (hmstate.trans h0.symm)
  | b => exact hnew 1 (by omega) (hmstate.trans h1.symm)

def singletonGraph : OpenGraph Unit where
  State := Unit
  step := fun _ _ _ => True

def singletonFrame : OpenFrame Unit where
  graph := singletonGraph
  init := fun _ => True
  admissible := fun _ => True
  envelope := fun _ => True
  admissible_subset_envelope := by simp
  fair := fun _ => True

def singletonExecution : Execution singletonGraph where
  state := fun _ => ()
  kind := fun _ => .internal
  edge := by simp [singletonGraph]

theorem singleton_possibleLive : singletonFrame.PossibleLive := by
  refine ⟨singletonExecution, trivial, ?_⟩
  intro n
  exact ⟨n, le_rfl, trivial⟩

theorem singleton_hasTerminalInit : singletonFrame.HasTerminalInit := by
  refine ⟨(), ?_, ?_⟩
  · exact ⟨(), trivial, ⟨@Path.nil Unit singletonGraph ()⟩⟩
  · intro s _
    cases s
    exact ⟨@Path.nil Unit singletonGraph ()⟩

/-- Theorem 17.15: open recurrence does not imply absence of an initial
component terminal target. -/
theorem possibleLive_not_imply_noTerminalInit :
    singletonFrame.PossibleLive ∧ ¬ singletonFrame.NoTerminalInit :=
  ⟨singleton_possibleLive, not_not_intro singleton_hasTerminalInit⟩

inductive BranchState where
  | r
  | l
  | q
  deriving DecidableEq, Repr

open BranchState

def branchGraph : OpenGraph Unit where
  State := BranchState
  step
    | .r, .internal, .l => True
    | .l, .internal, .l => True
    | .q, .internal, .q => True
    | .r, .coupling (), .q => True
    | _, _, _ => False

def branchFrame : OpenFrame Unit where
  graph := branchGraph
  init := (· = .r)
  admissible := (· = .r)
  envelope := (· = .r)
  admissible_subset_envelope := fun h => h
  fair := fun _ => True

private theorem branch_edge_from_l_target_l {kind : EdgeKind Unit} {t : BranchState}
    (edge : branchGraph.step .l kind t) : t = .l := by
  cases kind with
  | internal => cases t <;> simp [branchGraph] at edge ⊢
  | coupling port =>
      cases port
      cases t <;> simp [branchGraph] at edge

private theorem branch_edge_from_q_target_q {kind : EdgeKind Unit} {t : BranchState}
    (edge : branchGraph.step .q kind t) : t = .q := by
  cases kind with
  | internal => cases t <;> simp [branchGraph] at edge ⊢
  | coupling port =>
      cases port
      cases t <;> simp [branchGraph] at edge

private def branch_path_from_l_target_l :
    {t : BranchState} → Path branchGraph .l t → t = .l
  | _, .nil _ => rfl
  | _, .cons edge rest =>
      branch_path_from_l_target_l
        (Path.castSource (branch_edge_from_l_target_l edge) rest)
  termination_by t p => p.length
  decreasing_by simp

private def branch_path_from_q_target_q :
    {t : BranchState} → Path branchGraph .q t → t = .q
  | _, .nil _ => rfl
  | _, .cons edge rest =>
      branch_path_from_q_target_q
        (Path.castSource (branch_edge_from_q_target_q edge) rest)
  termination_by t p => p.length
  decreasing_by simp

private theorem branch_internal_edge_from_r_target_l {t : BranchState}
    (edge : branchGraph.step .r .internal t) : t = .l := by
  cases t <;> simp [branchGraph] at edge ⊢

private theorem branch_coupling_edge_from_r_target_q {t : BranchState}
    (edge : branchGraph.step .r (.coupling ()) t) : t = .q := by
  cases t <;> simp [branchGraph] at edge ⊢

private theorem branch_nonempty_path_from_r_not_r
    (p : Path branchGraph .r .r) (hlen : 1 ≤ p.length) : False :=
  match p with
  | .nil _ => by simp at hlen
  | .cons (kind := kind) edge rest => by
      cases kind with
      | internal =>
          have hm := branch_internal_edge_from_r_target_l edge
          have : BranchState.r = BranchState.l :=
            branch_path_from_l_target_l (hm ▸ rest)
          exact BranchState.noConfusion this
      | coupling port =>
          cases port
          have hm := branch_coupling_edge_from_r_target_q edge
          have : BranchState.r = BranchState.q :=
            branch_path_from_q_target_q (hm ▸ rest)
          exact BranchState.noConfusion this

theorem branch_reach_r : branchFrame.ReachInit .r :=
  ⟨.r, rfl, ⟨@Path.nil Unit branchGraph .r⟩⟩

theorem branch_reach_l : branchFrame.ReachInit .l := by
  refine ⟨.r, rfl, ⟨?_⟩⟩
  have edge : branchGraph.step .r .internal .l := trivial
  simpa [branchFrame] using Path.single edge

theorem branch_reach_q : branchFrame.ReachInit .q := by
  refine ⟨.r, rfl, ⟨?_⟩⟩
  have edge : branchGraph.step .r (.coupling ()) .q := trivial
  simpa [branchFrame] using Path.single edge

theorem branch_noTerminalInit : branchFrame.NoTerminalInit := by
  rintro ⟨target, _, hterminal⟩
  cases target with
  | r =>
      obtain ⟨path⟩ := hterminal .l branch_reach_l
      exact BranchState.noConfusion (branch_path_from_l_target_l path)
  | l =>
      obtain ⟨path⟩ := hterminal .q branch_reach_q
      exact BranchState.noConfusion (branch_path_from_q_target_q path)
  | q =>
      obtain ⟨path⟩ := hterminal .l branch_reach_l
      exact BranchState.noConfusion (branch_path_from_l_target_l path)

theorem branch_not_possibleLive : ¬ branchFrame.PossibleLive := by
  rintro ⟨x, hxInit, hrecurrent⟩
  change Execution branchGraph at x
  obtain ⟨m, hm, hmA⟩ := hrecurrent 1
  change x.state 0 = BranchState.r at hxInit
  change x.state m = BranchState.r at hmA
  have endpointEq : x.state (0 + m) = x.state m := by congr 1; omega
  let p0 : Path branchGraph (x.state 0) (x.state m) :=
    Path.castTarget endpointEq (x.segment 0 m)
  have hpLength : p0.length = m := by
    simp [p0, x.segment_length]
  have stateEq0 : x.state 0 = BranchState.r := hxInit
  have stateEqM : x.state m = BranchState.r := hmA
  let p1 : Path branchGraph BranchState.r (x.state m) :=
    Path.castSource stateEq0 p0
  let p : Path branchGraph BranchState.r BranchState.r :=
    Path.castTarget stateEqM p1
  apply branch_nonempty_path_from_r_not_r p
  have : p.length = m := by simpa [p, p1] using hpLength
  omega

/-- The first nonimplication in Theorem 17.15. -/
theorem noTerminalInit_not_imply_possibleLive :
    branchFrame.NoTerminalInit ∧ ¬ branchFrame.PossibleLive :=
  ⟨branch_noTerminalInit, branch_not_possibleLive⟩

end ReferenceModels

end OpenDynamics

end ERIEC
