import ERIEC.OpenEvolution
import ERIEC.Graded

namespace ERIEC

namespace TemporalDC

open OpenEvolution

universe u v w

/-!
Endogenous time generated by an individual TRM.

The TRM generates occurrences and immediate transitions.  ERIE-C does not
generate those ticks: it verifies that each transition belongs to the TRM's
open dynamics and places DC certificates over the resulting local clock.
External timestamps are optional order-preserving observations of this clock.
-/

/-- Reflexive-transitive reachability generated by an immediate relation. -/
inductive Reachable {α : Type u} (next : α → α → Prop) : α → α → Prop
  | refl (a : α) : Reachable next a a
  | tail {a b c : α} : Reachable next a b → next b c → Reachable next a c

namespace Reachable

variable {α : Type u} {next : α → α → Prop}

theorem single {a b : α} (h : next a b) : Reachable next a b :=
  .tail (.refl a) h

theorem trans {a b c : α}
    (hab : Reachable next a b) (hbc : Reachable next b c) :
    Reachable next a c := by
  induction hbc with
  | refl => exact hab
  | tail hxy hyz ih => exact .tail ih hyz

end Reachable

/-- Occurrences produced by one TRM.  Distinct occurrences may carry the same
configuration, so recurrent dynamics do not collapse different clock ticks. -/
structure GeneratedTrace (A : OpenSystem.{u}) where
  Occurrence : Type v
  state : Occurrence → Config A
  next : Occurrence → Occurrence → Prop
  generated : ∀ {x y}, next x y → state y ∈ A.step (state x)

namespace GeneratedTrace

variable {A : OpenSystem.{u}} (T : GeneratedTrace.{u, v} A)

/-- The local endogenous clock: its arrows are paths generated by this TRM's
own immediate transitions. -/
def clock : Graded.ThinCategory T.Occurrence where
  leq := Reachable T.next
  refl := Reachable.refl
  trans := Reachable.trans

theorem immediate_is_time {x y : T.Occurrence} (h : T.next x y) :
    T.clock.leq x y :=
  Reachable.single h

theorem immediate_is_system_transition {x y : T.Occurrence}
    (h : T.next x y) :
    T.state y ∈ A.step (T.state x) :=
  T.generated h

end GeneratedTrace

/-- ERIE-C's read-only certification over a clock generated by a TRM. -/
structure Certification {A : OpenSystem.{u}} (T : GeneratedTrace.{u, v} A) where
  dcHolds : T.Occurrence → Prop

/-- Read-only action evidence supplied by a concrete TRM trace.  It is kept
separate from generated time so an implementation without such evidence is
not forced to invent action ticks. -/
structure ActionObservation {A : OpenSystem.{u}}
    (T : GeneratedTrace.{u, v} A) where
  executes : T.Occurrence → Prop

/-- A path whose initial occurrence and every appended occurrence retain DC. -/
inductive DCPreservingReachable {A : OpenSystem.{u}}
    {T : GeneratedTrace.{u, v} A} (C : Certification T) :
    T.Occurrence → T.Occurrence → Prop
  | refl (x : T.Occurrence) (hx : C.dcHolds x) :
      DCPreservingReachable C x x
  | tail {x y z : T.Occurrence} :
      DCPreservingReachable C x y → T.next y z → C.dcHolds z →
        DCPreservingReachable C x z

namespace DCPreservingReachable

variable {A : OpenSystem.{u}} {T : GeneratedTrace.{u, v} A}
  {C : Certification T}

theorem source_dc {x y : T.Occurrence}
    (h : DCPreservingReachable C x y) : C.dcHolds x := by
  induction h with
  | refl hx => exact hx
  | tail _ _ _ ih => exact ih

theorem target_dc {x y : T.Occurrence}
    (h : DCPreservingReachable C x y) : C.dcHolds y := by
  cases h with
  | refl hx => exact hx
  | tail _ _ hz => exact hz

theorem trans {x y z : T.Occurrence}
    (hxy : DCPreservingReachable C x y)
    (hyz : DCPreservingReachable C y z) :
    DCPreservingReachable C x z := by
  induction hyz with
  | refl => exact hxy
  | tail _ hyz hdc ih => exact .tail ih hyz hdc

end DCPreservingReachable

namespace Certification

variable {A : OpenSystem.{u}} {T : GeneratedTrace.{u, v} A}
  (C : Certification T)

/-- Occurrences certified as retaining DC. -/
abbrev MaintenanceOccurrence := {x : T.Occurrence // C.dcHolds x}

/-- The maintenance subclock.  Its arrows contain evidence that DC holds
throughout the generated path, not merely at its endpoints. -/
def maintenanceClock : Graded.ThinCategory C.MaintenanceOccurrence where
  leq := fun x y => DCPreservingReachable C x.1 y.1
  refl := fun x => .refl x.1 x.2
  trans := DCPreservingReachable.trans

end Certification

namespace ActionObservation

variable {A : OpenSystem.{u}} {T : GeneratedTrace.{u, v} A}
  (O : ActionObservation T)

/-- The action clock can skip maintenance-only occurrences while retaining
their causal order in the underlying TRM trace. -/
def actionClock : Graded.ThinCategory {x : T.Occurrence // O.executes x} where
  leq := fun x y => Reachable T.next x.1 y.1
  refl := fun x => .refl x.1
  trans := Reachable.trans

end ActionObservation

namespace Certification

variable {A : OpenSystem.{u}} {T : GeneratedTrace.{u, v} A}
  (C : Certification T)

/-- Existing functional-termination criterion on an actual TRM transition. -/
def FunctionalTerminationStep (x y : T.Occurrence) : Prop :=
  T.next x y ∧ C.dcHolds x ∧ ¬ C.dcHolds y

/-- Dormancy-like classification: DC capability remains, but this occurrence
is not an action tick.  It is derived, not a new lifecycle state. -/
def OperationalPauseAt (O : ActionObservation T) (x : T.Occurrence) : Prop :=
  C.dcHolds x ∧ ¬ O.executes x

/-- A DC-preserving endogenous path from a pause to a later action occurrence. -/
def ResumesAlong (O : ActionObservation T) (x y : T.Occurrence) : Prop :=
  C.OperationalPauseAt O x ∧
    DCPreservingReachable C x y ∧ O.executes y

theorem resumes_target_dc (O : ActionObservation T) {x y : T.Occurrence}
    (h : C.ResumesAlong O x y) :
    C.dcHolds y :=
  DCPreservingReachable.target_dc h.2.1

theorem resumes_not_terminated (O : ActionObservation T) {x y : T.Occurrence}
    (h : C.ResumesAlong O x y) : ¬ C.FunctionalTerminationStep x y := by
  intro ht
  exact ht.2.2 (C.resumes_target_dc O h)

end Certification

/-- External timestamps observe an already generated local clock.  They do
not create its occurrences. -/
structure ExternalRealization {A : OpenSystem.{u}}
    (T : GeneratedTrace.{u, v} A)
    {External : Type w} (external : Graded.ThinCategory External) where
  stamp : T.Occurrence → External
  monotone : ∀ {x y}, Reachable T.next x y →
    external.leq (stamp x) (stamp y)

namespace ExternalRealization

variable {A : OpenSystem.{u}} {T : GeneratedTrace.{u, v} A}
  {External : Type w} {external : Graded.ThinCategory External}

theorem preserves_local_order (R : ExternalRealization T external)
    {x y : T.Occurrence} (h : T.clock.leq x y) :
    external.leq (R.stamp x) (R.stamp y) :=
  R.monotone h

end ExternalRealization

end TemporalDC

end ERIEC
