import ERIEC.Sensitivity
import Mathlib.Analysis.InnerProductSpace.Positive
import Mathlib.Analysis.InnerProductSpace.Rayleigh
import Mathlib.Analysis.InnerProductSpace.Spectrum

open scoped RealInnerProductSpace

namespace ERIEC

namespace World

/-!
Minimal formal layer for the actuated world `Wld`.

The numerical Julia implementation extracts an eigenspace of
`L = T^* ∘ T` near eigenvalue `1`. Lean fixes the structural core first:
`L` is the body/sensitivity loop operator, and a nonzero fixed vector of `L`
is a nontrivial actuated-world direction. Spectral approximation is a numerical
layer, not part of this file.
-/

/-- The world loop operator `L = T^* ∘ T` on action space. -/
noncomputable def worldLoop {m e : Nat}
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m)) :
    EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m) :=
  (Sens.T_w_adjoint sigma a).comp (Sens.T_w sigma a)

theorem worldLoop_def {m e : Nat}
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m)) :
    worldLoop sigma a = (Sens.T_w_adjoint sigma a).comp (Sens.T_w sigma a) :=
  rfl

/-- A vector fixed by the world loop, corresponding to eigenvalue `1`. -/
def WorldFixedVector {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (x : EuclideanSpace ℝ (Fin m)) : Prop :=
  L x = x

/-- `Wld` is nontrivial when the loop has a nonzero fixed direction. -/
def WldNontrivial {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) : Prop :=
  ∃ x : EuclideanSpace ℝ (Fin m), x ≠ 0 ∧ WorldFixedVector L x

/-- Residual-norm admissible set from §6.2. -/
def Eeta {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (eta : ℝ) : Set (EuclideanSpace ℝ (Fin m)) :=
  {x | ‖L x - x‖ ≤ eta * ‖x‖}

/-- Spectral band generated by eigenvectors whose eigenvalues lie near one. -/
def Wld_band {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (eta : ℝ) : Submodule ℝ (EuclideanSpace ℝ (Fin m)) :=
  Submodule.span ℝ
    {x | ∃ lambda : ℝ, |lambda - 1| ≤ eta ∧ L x = lambda • x}

/-- Linear fixed-point subspace of `L`. -/
def Fix {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) :
    Submodule ℝ (EuclideanSpace ℝ (Fin m)) :=
  LinearMap.ker (L.toLinearMap - LinearMap.id)

theorem mem_Fix_iff {m : Nat}
    {L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)}
    {x : EuclideanSpace ℝ (Fin m)} :
    x ∈ Fix L ↔ L x = x := by
  simp [Fix, sub_eq_zero]

/-- The spectral span is invariant under `L`. -/
theorem band_invariant {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (eta : ℝ) {x : EuclideanSpace ℝ (Fin m)}
    (hx : x ∈ Wld_band L eta) :
    L x ∈ Wld_band L eta := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨lambda, hBand, hEigen⟩
      rw [hEigen]
      exact Submodule.smul_mem _ lambda
        (Submodule.subset_span ⟨lambda, hBand, hEigen⟩)
  | zero => simp
  | add x y _ _ hx hy => simpa using Submodule.add_mem _ hx hy
  | smul a x _ hx => simpa using Submodule.smul_mem _ a hx

/-- At zero bandwidth, the spectral span is exactly the fixed subspace. -/
theorem band_zero_eq_fix {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) :
    Wld_band L 0 = Fix L := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    intro x hx
    rcases hx with ⟨lambda, hBand, hEigen⟩
    have hLambda : lambda = 1 := by
      have : lambda - 1 = 0 := abs_nonpos_iff.mp hBand
      linarith
    apply mem_Fix_iff.mpr
    simpa [hLambda] using hEigen
  · intro x hx
    apply Submodule.subset_span
    refine ⟨1, by simp, ?_⟩
    simpa using mem_Fix_iff.mp hx

/-- Spectral bandwidth is monotone in its tolerance. -/
theorem band_mono {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    {eta eta' : ℝ} (hEta : eta ≤ eta') :
    Wld_band L eta ≤ Wld_band L eta' := by
  apply Submodule.span_mono
  rintro x ⟨lambda, hBand, hEigen⟩
  exact ⟨lambda, hBand.trans hEta, hEigen⟩

theorem fixedVector_witnesses_nontrivial {m : Nat}
    {L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)}
    {x : EuclideanSpace ℝ (Fin m)}
    (hx0 : x ≠ 0)
    (hfix : WorldFixedVector L x) :
    WldNontrivial L :=
  ⟨x, hx0, hfix⟩

/-- The loop inner product reduces to the sensitivity inner product. -/
theorem worldLoop_inner {m e : Nat}
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m))
    (x y : EuclideanSpace ℝ (Fin m)) :
    inner ℝ (worldLoop sigma a x) y =
      inner ℝ (Sens.T_w sigma a x) (Sens.T_w sigma a y) := by
  simpa [worldLoop, Sens.T_w_adjoint] using
    ContinuousLinearMap.adjoint_inner_left (Sens.T_w sigma a) y (Sens.T_w sigma a x)

/-- `L = T^* ∘ T` is symmetric with respect to the real inner product. -/
theorem worldLoop_symmetric {m e : Nat}
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m))
    (x y : EuclideanSpace ℝ (Fin m)) :
    inner ℝ (worldLoop sigma a x) y =
      inner ℝ x (worldLoop sigma a y) := by
  calc
    inner ℝ (worldLoop sigma a x) y =
        inner ℝ (Sens.T_w sigma a x) (Sens.T_w sigma a y) := by
          exact worldLoop_inner sigma a x y
    _ = inner ℝ x (worldLoop sigma a y) := by
          simpa [worldLoop, Sens.T_w_adjoint] using
            (ContinuousLinearMap.adjoint_inner_right
              (Sens.T_w sigma a) x (Sens.T_w sigma a y)).symm

/-- The Gram loop `T†T`, packaged as Mathlib's symmetry predicate. -/
theorem worldLoop_isSymmetric {m e : Nat}
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m)) :
    (worldLoop sigma a).toLinearMap.IsSymmetric := by
  intro x y
  exact worldLoop_symmetric sigma a x y

/-- For a self-adjoint operator, the span of all eigenvectors in the unit
spectral band satisfies the residual-norm admissibility bound. The symmetry
hypothesis is essential: the statement is false for general non-normal maps. -/
theorem band_subset_Eeta {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (hL : L.toLinearMap.IsSymmetric) (eta : ℝ) :
    (Wld_band L eta : Set (EuclideanSpace ℝ (Fin m))) ⊆ Eeta L eta := by
  intro x hx
  by_cases hEta : 0 ≤ eta
  · let hdim : Module.finrank ℝ (EuclideanSpace ℝ (Fin m)) = m := by simp
    let b := hL.eigenvectorBasis hdim
    let eigenvalue := hL.eigenvalues hdim
    let bandSpace : Submodule ℝ (EuclideanSpace ℝ (Fin m)) :=
      { carrier := {x | ∀ i, ¬ |eigenvalue i - 1| ≤ eta → b.repr x i = 0}
        zero_mem' := by simp
        add_mem' := by
          intro u v hu hv i hi
          simp [hu i hi, hv i hi]
        smul_mem' := by
          intro c u hu i hi
          simp [hu i hi] }
    have hBandLe : Wld_band L eta ≤ bandSpace := by
      apply Submodule.span_le.mpr
      rintro u ⟨lambda, hLambda, hEigen⟩
      intro i hi
      have hCoordinate := hL.eigenvectorBasis_apply_self_apply hdim u i
      change b.repr (L u) i = eigenvalue i * b.repr u i at hCoordinate
      rw [hEigen] at hCoordinate
      have hEq : eigenvalue i * b.repr u i = lambda * b.repr u i := by
        simpa [b, eigenvalue] using hCoordinate.symm
      have hNe : eigenvalue i ≠ lambda := by
        intro h
        apply hi
        simpa [h] using hLambda
      have hMul : (eigenvalue i - lambda) * b.repr u i = 0 := by
        linarith
      exact (mul_eq_zero.mp hMul).resolve_left (sub_ne_zero.mpr hNe)
    have hxBand : x ∈ bandSpace := hBandLe hx
    have hCoordinate : ∀ i,
        b.repr (L x - x) i = (eigenvalue i - 1) * b.repr x i := by
      intro i
      have hApply := hL.eigenvectorBasis_apply_self_apply hdim x i
      change b.repr (L x) i = eigenvalue i * b.repr x i at hApply
      simp only [map_sub, PiLp.sub_apply]
      rw [hApply]
      simp [b, eigenvalue]
      ring
    have hPointwise : ∀ i,
        ((eigenvalue i - 1) * b.repr x i) ^ 2 ≤
          eta ^ 2 * (b.repr x i) ^ 2 := by
      intro i
      by_cases hi : |eigenvalue i - 1| ≤ eta
      · have hSq : |eigenvalue i - 1| ^ 2 ≤ eta ^ 2 :=
          (sq_le_sq₀ (abs_nonneg _) hEta).mpr hi
        simpa [mul_pow, sq_abs] using
          mul_le_mul_of_nonneg_right hSq (sq_nonneg (b.repr x i))
      · have hZero : b.repr x i = 0 := hxBand i hi
        simp [hZero]
    have hSq : ‖L x - x‖ ^ 2 ≤ (eta * ‖x‖) ^ 2 := by
      calc
        ‖L x - x‖ ^ 2 = ‖b.repr (L x - x)‖ ^ 2 := by
          rw [b.repr.norm_map]
        _ = ∑ i, (b.repr (L x - x) i) ^ 2 :=
          EuclideanSpace.real_norm_sq_eq _
        _ = ∑ i, ((eigenvalue i - 1) * b.repr x i) ^ 2 := by
          apply Finset.sum_congr rfl
          intro i _
          rw [hCoordinate i]
        _ ≤ ∑ i, eta ^ 2 * (b.repr x i) ^ 2 :=
          Finset.sum_le_sum fun i _ => hPointwise i
        _ = eta ^ 2 * ‖b.repr x‖ ^ 2 := by
          rw [EuclideanSpace.real_norm_sq_eq, Finset.mul_sum]
        _ = (eta * ‖x‖) ^ 2 := by
          rw [b.repr.norm_map]
          ring
    exact (sq_le_sq₀ (norm_nonneg _) (mul_nonneg hEta (norm_nonneg _))).mp hSq
  · have hBandBot : Wld_band L eta = ⊥ := by
      apply le_antisymm
      · apply Submodule.span_le.mpr
        rintro u ⟨lambda, hLambda, _⟩
        exfalso
        exact hEta ((abs_nonneg _).trans hLambda)
      · exact bot_le
    rw [hBandBot] at hx
    have hx0 : x = 0 := by simpa using hx
    subst x
    simp [Eeta]

/-- The largest Rayleigh quotient. For finite-dimensional self-adjoint maps this
is the largest eigenvalue by the spectral theorem. -/
noncomputable def lambdaMax {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) : ℝ :=
  ⨆ x : {x : EuclideanSpace ℝ (Fin m) // x ≠ 0}, L.rayleighQuotient x

/-- The critical distance of the largest eigenvalue from the unit value. -/
noncomputable def chi {m : Nat}
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) : ℝ :=
  |1 - lambdaMax L|

/-- The unresolved critical-slowing claim from Conjecture 6.9.

`approachesCollapse` is deliberately an explicit interface: relating the
discrete collapse dynamics to a continuous world-loop trajectory is not yet a
theorem of the formal core.  The definition records the two conclusions that
would have to follow from such a bridge without asserting that the bridge or
the conjecture is inhabited. -/
def CriticalSlowingConjecture {S : Type*}
    (approachesCollapse : (ℕ → S) → Prop)
    (lambdaMaxAt recoveryTime : S → ℝ) : Prop :=
  ∀ trajectory, approachesCollapse trajectory →
    Filter.Tendsto (fun n ↦ lambdaMaxAt (trajectory n)) Filter.atTop (nhds 1) ∧
    Filter.Tendsto (fun n ↦ recoveryTime (trajectory n)) Filter.atTop Filter.atTop

/-- On a nonzero finite-dimensional self-adjoint space, `lambdaMax` is an
actual eigenvalue rather than merely a supremum. -/
theorem lambdaMax_hasEigenvalue {m : Nat} [NeZero m]
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (hL : L.toLinearMap.IsSymmetric) :
    Module.End.HasEigenvalue L.toLinearMap (lambdaMax L) := by
  exact hL.hasEigenvalue_iSup_of_finiteDimensional

/-- For the positive Gram loop `L = T†T`, the top eigenvalue is the squared
operator norm of `T`. -/
theorem lambdaMax_eq_normSq_T {m e : Nat} [NeZero m]
    (sigma : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin e))
    (a : EuclideanSpace ℝ (Fin m)) :
    lambdaMax (worldLoop sigma a) = ‖Sens.T_w sigma a‖ ^ 2 := by
  let T := Sens.T_w sigma a
  have hNonneg : ∀ x : EuclideanSpace ℝ (Fin m),
      0 ≤ (worldLoop sigma a).rayleighQuotient x := by
    intro x
    simp only [ContinuousLinearMap.rayleighQuotient,
      ContinuousLinearMap.reApplyInnerSelf_apply]
    rw [worldLoop_inner sigma a x x, real_inner_self_eq_norm_sq]
    exact div_nonneg (sq_nonneg _) (sq_nonneg _)
  have hBdd : BddAbove (Set.range fun x :
      {x : EuclideanSpace ℝ (Fin m) // x ≠ 0} =>
        (worldLoop sigma a).rayleighQuotient x) := by
    refine ⟨‖worldLoop sigma a‖, ?_⟩
    rintro _ ⟨x, rfl⟩
    exact (le_abs_self _).trans
      ((worldLoop sigma a).rayleighQuotient_le_norm x)
  let i : Fin m := ⟨0, Nat.pos_of_ne_zero (NeZero.ne m)⟩
  let x : EuclideanSpace ℝ (Fin m) := EuclideanSpace.single i 1
  have hx : x ≠ 0 := by simp [x]
  letI : Nonempty {x : EuclideanSpace ℝ (Fin m) // x ≠ 0} := ⟨⟨x, hx⟩⟩
  have hLambdaNonneg : 0 ≤ lambdaMax (worldLoop sigma a) := by
    exact (hNonneg x).trans
      (le_ciSup hBdd (⟨x, hx⟩ : {x : EuclideanSpace ℝ (Fin m) // x ≠ 0}))
  calc
    lambdaMax (worldLoop sigma a) = ‖worldLoop sigma a‖ := by
      apply le_antisymm
      · rw [lambdaMax]
        exact ciSup_le fun x => (le_abs_self _).trans
          ((worldLoop sigma a).rayleighQuotient_le_norm x)
      · rw [ContinuousLinearMap.norm_eq_iSup_rayleighQuotient
          (worldLoop sigma a) (worldLoop_isSymmetric sigma a)]
        apply ciSup_le
        intro x
        rw [abs_of_nonneg (hNonneg x)]
        by_cases hx : x = 0
        · simpa [hx] using hLambdaNonneg
        · exact le_ciSup hBdd
            (⟨x, hx⟩ : {x : EuclideanSpace ℝ (Fin m) // x ≠ 0})
    _ = ‖T‖ * ‖T‖ := by
      simpa [T, worldLoop, Sens.T_w_adjoint] using
        ContinuousLinearMap.norm_adjoint_comp_self T
    _ = ‖Sens.T_w sigma a‖ ^ 2 := by simp [T, pow_two]

/-- If the largest eigenvalue lies in the unit spectral band, that band has a
nonzero direction. -/
theorem band_nontrivial_of_chi_le {m : Nat} [NeZero m]
    (L : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m))
    (hL : L.toLinearMap.IsSymmetric) (eta : ℝ)
    (hChi : chi L ≤ eta) :
    Wld_band L eta ≠ ⊥ := by
  obtain ⟨x, hx⟩ := (lambdaMax_hasEigenvalue L hL).exists_hasEigenvector
  have hxBand : x ∈ Wld_band L eta := by
    apply Submodule.subset_span
    refine ⟨lambdaMax L, ?_, hx.apply_eq_smul⟩
    simpa [chi, abs_sub_comm] using hChi
  intro hBot
  rw [hBot] at hxBand
  exact hx.2 hxBand

end World

end ERIEC
